export interface AdministrativeUnit {
  province_code: string;
  province_name: string;
  province_ascii: string;
  district_name: string;
  district_ascii: string;
  commune_name: string;
  commune_ascii: string;
}

export const ADMINISTRATIVE_UNITS: AdministrativeUnit[] = [
  { province_code: "01", province_name: "Hà Nội", province_ascii: "Ha Noi", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "02", province_name: "Hà Giang", province_ascii: "Ha Giang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "04", province_name: "Cao Bằng", province_ascii: "Cao Bang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "06", province_name: "Bắc Kạn", province_ascii: "Bac Kan", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "08", province_name: "Tuyên Quang", province_ascii: "Tuyen Quang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "10", province_name: "Lào Cai", province_ascii: "Lao Cai", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "11", province_name: "Điện Biên", province_ascii: "Dien Bien", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "12", province_name: "Lai Châu", province_ascii: "Lai Chau", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "14", province_name: "Sơn La", province_ascii: "Son La", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "15", province_name: "Yên Bái", province_ascii: "Yen Bai", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "17", province_name: "Hoà Bình", province_ascii: "Hoa Binh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "19", province_name: "Thái Nguyên", province_ascii: "Thai Nguyen", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "20", province_name: "Lạng Sơn", province_ascii: "Lang Son", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "22", province_name: "Quảng Ninh", province_ascii: "Quang Ninh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "24", province_name: "Bắc Giang", province_ascii: "Bac Giang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "25", province_name: "Phú Thọ", province_ascii: "Phu Tho", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "26", province_name: "Vĩnh Phúc", province_ascii: "Vinh Phuc", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "27", province_name: "Bắc Ninh", province_ascii: "Bac Ninh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "30", province_name: "Hải Dương", province_ascii: "Hai Duong", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "31", province_name: "Hải Phòng", province_ascii: "Hai Phong", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "33", province_name: "Hưng Yên", province_ascii: "Hung Yen", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "34", province_name: "Thái Bình", province_ascii: "Thai Binh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "35", province_name: "Hà Nam", province_ascii: "Ha Nam", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "36", province_name: "Nam Định", province_ascii: "Nam Dinh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "37", province_name: "Ninh Bình", province_ascii: "Ninh Binh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "38", province_name: "Thanh Hóa", province_ascii: "Thanh Hoa", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "40", province_name: "Nghệ An", province_ascii: "Nghe An", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "42", province_name: "Hà Tĩnh", province_ascii: "Ha Tinh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "44", province_name: "Quảng Bình", province_ascii: "Quang Binh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "45", province_name: "Quảng Trị", province_ascii: "Quang Tri", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "46", province_name: "Thừa Thiên Huế", province_ascii: "Thua Thien Hue", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "48", province_name: "Đà Nẵng", province_ascii: "Da Nang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "49", province_name: "Quảng Nam", province_ascii: "Quang Nam", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "51", province_name: "Quảng Ngãi", province_ascii: "Quang Ngai", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "52", province_name: "Bình Định", province_ascii: "Binh Dinh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "54", province_name: "Phú Yên", province_ascii: "Phu Yen", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "56", province_name: "Khánh Hòa", province_ascii: "Khanh Hoa", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "58", province_name: "Ninh Thuận", province_ascii: "Ninh Thuan", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "60", province_name: "Bình Thuận", province_ascii: "Binh Thuan", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "62", province_name: "Kon Tum", province_ascii: "Kon Tum", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "64", province_name: "Gia Lai", province_ascii: "Gia Lai", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "66", province_name: "Đắk Lắk", province_ascii: "Dak Lak", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "67", province_name: "Đắk Nông", province_ascii: "Dak Nong", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "68", province_name: "Lâm Đồng", province_ascii: "Lam Dong", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "70", province_name: "Bình Phước", province_ascii: "Binh Phuoc", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "72", province_name: "Tây Ninh", province_ascii: "Tay Ninh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "74", province_name: "Bình Dương", province_ascii: "Binh Duong", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "75", province_name: "Đồng Nai", province_ascii: "Dong Nai", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "77", province_name: "Bà Rịa - Vũng Tàu", province_ascii: "Ba Ria - Vung Tau", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "79", province_name: "Hồ Chí Minh", province_ascii: "Ho Chi Minh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "80", province_name: "Long An", province_ascii: "Long An", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "82", province_name: "Tiền Giang", province_ascii: "Tien Giang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "83", province_name: "Bến Tre", province_ascii: "Ben Tre", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "84", province_name: "Trà Vinh", province_ascii: "Tra Vinh", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "86", province_name: "Vĩnh Long", province_ascii: "Vinh Long", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "87", province_name: "Đồng Tháp", province_ascii: "Dong Thap", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "89", province_name: "An Giang", province_ascii: "An Giang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "91", province_name: "Kiên Giang", province_ascii: "Kien Giang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "92", province_name: "Cần Thơ", province_ascii: "Can Tho", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "93", province_name: "Hậu Giang", province_ascii: "Hau Giang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "94", province_name: "Sóc Trăng", province_ascii: "Soc Trang", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "95", province_name: "Bạc Liêu", province_ascii: "Bac Lieu", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" },
  { province_code: "96", province_name: "Cà Mau", province_ascii: "Ca Mau", district_name: "", district_ascii: "", commune_name: "", commune_ascii: "" }
];
